### ISSUE TITLE
动画显示时长与错位

### ISSUE THREAD

**Issue by mj3622** [mj3622/BCCR_Impact#7]
@pxxxl  我有以下两个疑问：
1. 敌人在移动时受击可能出现特效在移动前的位置
2. 由于是事件处理器每处理一次事件完成一次动画效果（拆分成十段），这样是否会出现处理速度过快导致显示时间过短的问题。

对于第一个问题，只要在传入参数时注意即可解决，但是对于第二个问题想听听您的看法

**Comment by pxxxl** [comment]
显示时间过短是什么意思？

**Comment by mj3622** [comment]
> 显示时间过短是什么意思？

假设处理器10ms处理一轮，那么这一轮的动画也只会持续10ms
